is_train: True
ddp: False
stat: ts
root_path: ./
out_path: ./outputs/audio2pose/
project: semantic_transformer_5_mask
data_path: ./datasets/ted_expressive_dataset/
e_path:  fgd/last_499.bin #AESKConvZero_240.bin
eval_model: motion_autoencoder
e_name: HalfEmbeddingNet
test_ckpt: /data/clusterfs/mld/users/lanliu/SIGGRAGH_2024/DDL_1/SemDiffusion_latent_3_ted/beat_pre/sem_ted/last_20.bin
data_path_1: /data/clusterfs/mld/users/lanliu/SIGGRAGH_2024/DDL_1/SemDiffusion_latent_3_ted/beat_pre/
#vae_eval_dim: 141
vae_test_len: 64
vae_test_dim: 258
vae_test_stride: 20
vae_length: 512
vae_codebook_size: 256
vae_layer: 2
vae_grow: [1,1,2,1]
variational: False
dataset_name: ted
addTextCond: False
# data config
training_speakers: [2] #[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30]
additional_data: False
cache_path: /data/clusterfs/mld/users/lanliu/SIGGRAGH_2024/DDL_1/SemDiffusion_latent_3_ted/datasets/ted_expressive_dataset/
dataset: ted_sep
new_cache: False
test_data_path: /data/clusterfs/mld/users/lanliu/SIGGRAGH_2024/DDL_1/SemDiffusion_latent_3_ted/datasets/ted_expressive_dataset/test_cahe_pickle/
# motion config
ori_joints: beat_141
tar_joints: beat_141
pose_rep: bvh_rot
pose_norm: False
pose_fps: 30
rot6d: True
pre_frames: 4
pose_dims: 282
pose_length: 34
stride: 10
test_length: 64
motion_f: 256
m_pre_encoder: null
m_encoder: null
m_fix_pre: False

# audio config
audio_rep: onset+amplitude
audio_sr: 16000
audio_fps: 16000
audio_norm: False
audio_f: 256
# a_pre_encoder: tcn_camn
# a_encoder: none
# a_fix_pre: False
# text config
word_rep: textgrid
word_index_num: 26644
word_dims: 300
freeze_wordembed: False
wordembed_path: /data/clusterfs/mld/users/lanliu/SIGGRAGH_2024/DDL_1/SemDiffusion_latent_3_ted/datasets/ted_expressive_dataset/crawl-300d-2M-subword.bin
word_f: 256
t_pre_encoder: fasttext
t_encoder: null
t_fix_pre: False

# facial config
facial_rep: smplxflame_30
facial_dims: 100
facial_norm: False
facial_f: 0
f_pre_encoder: null
f_encoder: null
f_fix_pre: False
# speaker config
id_rep: onehot
speaker_f: 0
PE : ppe_sinu


# model config
batch_size: 1024
# warmup_epochs: 1
# warmup_lr: 1e-6
lr_base: 5e-4
model: semantic_transformer
g_name: SemanticsLatentTransformer
trainer: semanticted_transformer
hidden_size: 768
n_layer: 1
 
rec_weight: 1
grad_norm: 0.5
epochs: 40
test_period: 1
lu: 1
lh: 1
cl: 1
cf: 0
cu: 1
ch: 1

latent_dim: 256
num_layers: 12
num_heads: 8
quant_factor: 0   # do not change this value
intermediate_size: 384
audio_dim: 256  
one_hot_dim: 256
